### ISSUE TITLE
What are the accredited papers to achieve these models?

### ISSUE THREAD

**Issue by mohamd34** [Horacehxw/traffic_simulation#4]
Any links for the sources (papers, links,....etc), that you used to achieve these models please?

**Comment by Horacehxw** [comment]
Python traffic simulation libarary based on Martin Treiber's  Java applet from: http://www.traffic-simulation.de/. Implement IDM follower model and Lanechange model.

**Comment by Horacehxw** [comment]
If you want to cite this repository for Python implementation, just use the web link in github.
